// Code generated by MCHP Chatbot
/*
� [2026] Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms, you may use Microchip 
    software and any derivatives exclusively with Microchip products. 
    You are responsible for complying with 3rd party license terms  
    applicable to your use of 3rd party software (including open source  
    software) that may accompany Microchip software. SOFTWARE IS ?AS IS.? 
    NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS 
    SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT,  
    MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT 
    WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY 
    KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF 
    MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE 
    FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP?S 
    TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL NOT 
    EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR 
    THIS SOFTWARE.
*/

#include "hal.h"
#include "systick/systick.h"
#include "T1S/t1s_lwip.h"
#include "T1S/udp_perf_client.h"
#include "X2Cscope/X2Cscope.h"
#include "app.h"

#include <stdio.h>

/*
    Main application
*/


int main(void)
{
    HAL_Init();
    SysTick_Initialize();
    APP_Buttons_Init();

    printf("dsPIC33AK512MC510 + FOC + T1S\r\n");

    T1S_init();
    X2Cscope_Init();

    bool iperf_running = false;

    while(1)
    {
        X2Cscope_Communicate();

        T1S_execute();
        APP_Buttons_Task();

        if (APP_Button_WasPressed(APP_BTN_SW1))
        {
            if (iperf_running)
            {
                iperf_stop_application();
                printf("iperf test stopped\r\n");
                iperf_running = false;
            }
            else
            {
                iperf_start_application();
                printf("iperf test started\r\n");
                iperf_running = true;
            }
        }
    }
}
